### ISSUE TITLE
have trouble in updating submodule

### ISSUE THREAD

**Issue by JudyZhou95** [Oneplus/twpipe#6]
I got these errors when updating submodule. 
```
Cloning into '/export/a12/yzhou2/twpipe/dynet'...
Cloning into '/export/a12/yzhou2/twpipe/dynet_layer'...
error: no such remote ref 3c4665b3d5346cd7419d6db91987cffa80537758
Fetched in submodule path 'dynet', but it did not contain 3c4665b3d5346cd7419d6db91987cffa80537758. Direct fetching of that commit failed.
```

**Comment by Oneplus** [comment]
I believed the problem was related with dynet source tree. But you can solve it by specifying another version of dynet. You can do it with the following commands after running `git submodule update`:
```
cd dynet
git checkout 2.1
```
I've tested it on Ubuntu 16.04 and the compilation worked. If there is any problem, please let me know.

**Comment by Oneplus** [comment]
I believe the compilation problem is solved. So I will close this issue.
